### PR TITLE
Combi_params error

### PR DESCRIPTION
**Pull request by Emblanc**
Changing the function to read the sim_scheme.csv file and adding a test for the combi_param bug

### CODE REVIEW

**Comment by Emblanc** [comment]
This pull_request solves issue #71 
It is ready to be merged

**Comment by Emblanc** [comment]
I have done more tests, and I think this time, the pull-request is really ready to be merged

**Comment by christian34** [comment]
Did you try the float_precision='high' in read_csv ?

**Comment by christian34** [comment]
The test is probably wrong : it does not raise the bug on my machine . 
It could also be simplified using the 'test_project' syntax (instead of the 'test_command_line' syntax) and assertion can be made on counting rows of p.combi_params (which avoid recopy of read_itable in test file)

**Comment by Emblanc** [comment]
The float_precision='high' in read_csv seems to be working, thank you ! (And it is much simpler than the current proposed solution). I am going to run a few more tests before I change the file.

I will also put the test in the test_project file, using the correct syntax.
Regarding the failure to reproduce the bug, I am not sure what causes it, but I have noticed it too. The bug may or may not occur depending on the computer (I think that it might be related to the version of a library maybe ?)

I have observed the following results (I do not know if it is relevant) : 

computer1 : pandas 0.21.1 -> the test does not raise the bug
computer2 : pandas 0.23.4 -> the test raises the bug

**Pull request merged**
