### PR TITLE
Debug crop scheme

### PR DESCRIPTION
**Pull request by christian34**
Externalise and test crop_sheme functions

### CODE REVIEW

**Comment by christian34** [comment]
Ok the global test passes on the branch !

**Comment by Emblanc** [comment]
I checked the expected results for test_crop_mesh_for_nplants and I agree with them

**Comment by Emblanc** [comment]
The simulations we run for tests are no longer the right ones. I will change the sim_schemes.csv accordingly

**Comment by Emblanc** [comment]
The centre/border plants are no longer well defined.
For example, when running the sim_scheme_test_combi_params_err.csv, there should be 182 plants, including 58 that are centre plants. Instead, all 182 plants are considered to be in the centre of the plot.

**Comment by christian34** [comment]
Okay, thanks for the report ! I will include a test for securing the control of the repartition of border / center plants !

**Comment by christian34** [comment]
Oups I forgot to pass border distance to the central domain function : things should be better now...
I will still write a test !

**Comment by Emblanc** [comment]
Thank you, it seems to be working fine now !

**Pull request merged**
