### PR TITLE
Turtle sky

### LINKED ISSUE #60: Change the sky
Currently the sky used in WALTer is created via Caribu with the following parameters : 
nb_azimuth = 5
nb_zenith = 4
and we use only diffuse radiation.

### PR DESCRIPTION
**Pull request by christian34**
Add import of 46 sector sky discretisation (close #60)

@Emblanc :the 46 sky model could be used as the previous one, ie using a soc sky radiance model (current state), or used together with meteo data and geographical location to have more realistic skies (clear sky, sun, ...)

### CODE REVIEW

**Comment by Emblanc** [comment]
I tested the new sky, but there seems to be a problem : with the turtle sky, the plot intercepts about 15 times more light than with the previous sky (thus the plot intercepts a lot more than the incident light)

intercepted_light

**Comment by Emblanc** [comment]
The meteorological data for light are expressed in μmolPAR / m² summed over the day.

**Comment by christian34** [comment]
@Emblanc I have added turtle 1, 6 and 16 (in addition to turtle46) to allow performing the tests with a lower number of turtle sectors. You will need astk >=2.1.0 for this. To do so get astk on github, cd to astk directory and run python setup.py install in your conda env.

**Comment by Emblanc** [comment]
I don't know if this PR is supposed to be ready, but there is an error when I run this version of the model:
>TypeError: caribu_scene() takes exactly 5 arguments (3 given)

**Pull request merged**
