### PR TITLE
Curved leaves

### LINKED ISSUE #35: Curved leaves
Adding a curvature of the leaves to improve realism

### PR DESCRIPTION
**Pull request by christian34**
This branch is build on top of clean geometry : it should be merged after. (and close #35)

I replace the walter shape with the curved cereals shape, if you want to test. Some easy improvement could be made to simulate the progressive curvature of leaves as a function of leaf development. I will add that before merging.

### CODE REVIEW

**Comment by christian34** [comment]
@Emblanc We will have also to define whether you want to control directly leaf area or (leaf length + leaf width) only (leaf area being a function of these + leaf shape)

**Comment by Emblanc** [comment]
> @Emblanc We will have also to define whether you want to control directly leaf area or (leaf length + leaf width) only (leaf area being a function of these + leaf shape)

I discussed it with Jérôme and we think that it is best to control just leaf length and leaf width because these parameters are already well fitted to experimental data in the model.
It is our understanding that it should be easier and faster with this option (just leaf length and width) because it was already how leaves were coded before we added the curvature. Are we right to believe so ?

Also, do you think that we will have to rethink the computation of the GAI now that leaves are curved ?

**Comment by christian34** [comment]
To do : adjust the polynomial coefficient on wheat data (but keep parametric leaf). The control of the shape is kept with length on width

**Comment by Emblanc** [comment]
To do : adapt the calculation of the visible blade surface to the new shape

**Comment by Emblanc** [comment]
We choose to use the shape parameter for Soissons leaves from the publication of Tino & al. We will keep the impact of the rank of the leaf on the shape parameter (different parameter values for leaves of higher rank than the flag leaf)

**Comment by Emblanc** [comment]
> /home/emmanuelle/WALTer_Dvpt/src/walter/project.py:244:
>  Warning: Cannot find geometry for module @g
>  lstring = lsys.iterate()

**Comment by christian34** [comment]
may be add a mini lsystem to test/visualise leaf shape

**Comment by Emblanc** [comment]
To do : create a simple script to visualize leafs with different parameterization

**Comment by Emblanc** [comment]
To do : test if function leaf_area returns the same result as the primitive area

**Comment by Emblanc** [comment]
Despite the new argument epsilonL set to 10^-1, I still get the following warning : 

> Warning: Cannot find geometry for module @g

**Comment by christian34** [comment]
Currently if compensate = true for leaf meshing, shfit inligh test simulation drop  to 51 % variation for plant 3 : @christian34 : check if this case is due to leaves leading to caribu flat triangle error

**Comment by christian34** [comment]
The two previous commit close #82

**Comment by Emblanc** [comment]
There is a problem with the representation of the curved leaves.
It seems that, once the blades reach their full size, they are represented as very short, round leaves...
Here is a GIF to show what I mean : 
Bug_dvpt_curved_leaves

**Comment by pradal** [comment]
It seems that the length is wrong compared to the leaf surface. Then all the deformation is applied to the radius.

**Comment by christian34** [comment]
Funny bug !
 Does it persist after my last commit ?
If yes may be check that output value for visible length, final length and width are okay

**Comment by Emblanc** [comment]
The bug persists despite your last commit.
I checked the output and everything seems ok

**Comment by Emblanc** [comment]
Todo : suppress parameter curvature_max -> curvature will then be in degrees

**Comment by christian34** [comment]
The strange leaf bug should have gone now!

**Comment by Emblanc** [comment]
The bug seems to be gone thank you !

However, the parameter curvature does not seem to work as expected. The code states : 
> curvature = leaf angular curvature (tip angle - insertion angle, degree)
But from the tests I have run, it seems that curvature is just the angle between the base and the tip of the blade. Which means that if insertion_angle = curvature, the blade is completely straight.

**Comment by christian34** [comment]
Okay, the behavior is now as expected I think !

**Pull request merged**
